services:
  docs:
    image: messaging_service_local_docs
    container_name: messaging_service_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./messaging_service:/app/messaging_service:z
    ports:
      - '9000:9000'
    command: /start-docs
