# Generated by Django 5.1.11 on 2025-08-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='type',
        ),
        migrations.AlterField(
            model_name='participant',
            name='identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
