# Generated by Django 5.1.11 on 2025-08-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_participant_type_alter_participant_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
    ]
